
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action dndAction1;
	
	private global::Gtk.Action btnOpenFile;
	
	private global::Gtk.Action btnSaveAction;
	
	private global::Gtk.Action closeAction;
	
	private global::Gtk.ToggleAction applyHeader;
	
	private global::Gtk.Action addAction1;
	
	private global::Gtk.Action copyAction;
	
	private global::Gtk.Action pasteAction;
	
	private global::Gtk.Action cutAction;
	
	private global::Gtk.Action addAction;
	
	private global::Gtk.Action harddiskAction1;
	
	private global::Gtk.Action harddiskAction;
	
	private global::Gtk.ToggleAction selectFontAction;
	
	private global::Gtk.Action justifyCenterAction;
	
	private global::Gtk.Action justifyLeftAction;
	
	private global::Gtk.Action justifyRightAction;
	
	private global::Gtk.Action dialogInfoAction;
	
	private global::Gtk.Action preferencesAction;
	
	private global::Gtk.Action printAction;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action openAction;
	
	private global::Gtk.Action saveAction;
	
	private global::Gtk.Action saveAsAction1;
	
	private global::Gtk.Action Action;
	
	private global::Gtk.Action printAction1;
	
	private global::Gtk.Action Action1;
	
	private global::Gtk.Action quitAction;
	
	private global::Gtk.Action EditAction;
	
	private global::Gtk.Action copyAction1;
	
	private global::Gtk.Action pasteAction1;
	
	private global::Gtk.Action noAction;
	
	private global::Gtk.Action Action2;
	
	private global::Gtk.Action removeAction;
	
	private global::Gtk.Action removeAction1;
	
	private global::Gtk.Action deleteAction;
	
	private global::Gtk.Action addAction2;
	
	private global::Gtk.Action newAction;
	
	private global::Gtk.Action okAction;
	
	private global::Gtk.Action TextsizeAction;
	
	private global::Gtk.Action nine_Action;
	
	private global::Gtk.Action ten_Action;
	
	private global::Gtk.Action eleven_Action;
	
	private global::Gtk.Action twelve_Action;
	
	private global::Gtk.Action thirteen_Action;
	
	private global::Gtk.Action fourteen_Action;
	
	private global::Gtk.Action eighteen_Action;
	
	private global::Gtk.Action ViewAction;
	
	private global::Gtk.Action propertiesAction;
	
	private global::Gtk.Action dndAction;
	
	private global::Gtk.Action RecentFilesAction;
	
	private global::Gtk.Action clearAction;
	
	private global::Gtk.Action dialogInfoAction1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar2;
	
	private global::Gtk.Toolbar toolbar1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.NodeView lb;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.dndAction1 = new global::Gtk.Action ("dndAction1", null, global::Mono.Unix.Catalog.GetString ("new File"), "gtk-dnd");
		w1.Add (this.dndAction1, null);
		this.btnOpenFile = new global::Gtk.Action ("btnOpenFile", null, global::Mono.Unix.Catalog.GetString ("Open CSV File"), "gtk-open");
		w1.Add (this.btnOpenFile, null);
		this.btnSaveAction = new global::Gtk.Action ("btnSaveAction", null, global::Mono.Unix.Catalog.GetString ("Save CSV"), "gtk-floppy");
		w1.Add (this.btnSaveAction, null);
		this.closeAction = new global::Gtk.Action ("closeAction", null, global::Mono.Unix.Catalog.GetString ("delete Row"), "gtk-close");
		w1.Add (this.closeAction, null);
		this.applyHeader = new global::Gtk.ToggleAction ("applyHeader", global::Mono.Unix.Catalog.GetString ("First Row is Header"), global::Mono.Unix.Catalog.GetString ("First Row is Header on Open\nSave Header on Save"), "gtk-apply");
		this.applyHeader.DrawAsRadio = true;
		this.applyHeader.ShortLabel = global::Mono.Unix.Catalog.GetString ("First Row is Header");
		w1.Add (this.applyHeader, null);
		this.addAction1 = new global::Gtk.Action ("addAction1", null, global::Mono.Unix.Catalog.GetString ("add Row"), "gtk-add");
		w1.Add (this.addAction1, null);
		this.copyAction = new global::Gtk.Action ("copyAction", null, global::Mono.Unix.Catalog.GetString ("copy selected Row"), "gtk-copy");
		w1.Add (this.copyAction, null);
		this.pasteAction = new global::Gtk.Action ("pasteAction", null, global::Mono.Unix.Catalog.GetString ("paste Row on Selection"), "gtk-paste");
		w1.Add (this.pasteAction, null);
		this.cutAction = new global::Gtk.Action ("cutAction", null, null, "gtk-cut");
		w1.Add (this.cutAction, null);
		this.addAction = new global::Gtk.Action ("addAction", null, global::Mono.Unix.Catalog.GetString ("add Column"), "gtk-add");
		w1.Add (this.addAction, null);
		this.harddiskAction1 = new global::Gtk.Action ("harddiskAction1", null, global::Mono.Unix.Catalog.GetString ("Save to new File"), "gtk-harddisk");
		w1.Add (this.harddiskAction1, null);
		this.harddiskAction = new global::Gtk.Action ("harddiskAction", null, global::Mono.Unix.Catalog.GetString ("Test Button"), "gtk-harddisk");
		w1.Add (this.harddiskAction, null);
		this.selectFontAction = new global::Gtk.ToggleAction ("selectFontAction", null, global::Mono.Unix.Catalog.GetString ("Text-Size toggle 12 <-> 14"), "gtk-select-font");
		w1.Add (this.selectFontAction, null);
		this.justifyCenterAction = new global::Gtk.Action ("justifyCenterAction", null, global::Mono.Unix.Catalog.GetString ("Column align center"), "gtk-justify-center");
		w1.Add (this.justifyCenterAction, null);
		this.justifyLeftAction = new global::Gtk.Action ("justifyLeftAction", null, global::Mono.Unix.Catalog.GetString ("Column align left"), "gtk-justify-left");
		w1.Add (this.justifyLeftAction, null);
		this.justifyRightAction = new global::Gtk.Action ("justifyRightAction", null, global::Mono.Unix.Catalog.GetString ("Column align right"), "gtk-justify-right");
		w1.Add (this.justifyRightAction, null);
		this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", null, global::Mono.Unix.Catalog.GetString ("about"), "gtk-dialog-info");
		w1.Add (this.dialogInfoAction, null);
		this.preferencesAction = new global::Gtk.Action ("preferencesAction", null, null, "gtk-preferences");
		w1.Add (this.preferencesAction, null);
		this.printAction = new global::Gtk.Action ("printAction", null, null, "gtk-print");
		w1.Add (this.printAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.saveAction, null);
		this.saveAsAction1 = new global::Gtk.Action ("saveAsAction1", global::Mono.Unix.Catalog.GetString ("Save as ..."), null, "gtk-save-as");
		this.saveAsAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save as ...");
		w1.Add (this.saveAsAction1, "<Primary><Alt>s");
		this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("-"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("-");
		w1.Add (this.Action, null);
		this.printAction1 = new global::Gtk.Action ("printAction1", global::Mono.Unix.Catalog.GetString ("Print"), null, "gtk-print");
		this.printAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Print");
		w1.Add (this.printAction1, "<Primary>p");
		this.Action1 = new global::Gtk.Action ("Action1", global::Mono.Unix.Catalog.GetString ("-"), null, null);
		this.Action1.ShortLabel = global::Mono.Unix.Catalog.GetString ("-");
		w1.Add (this.Action1, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.quitAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.copyAction1 = new global::Gtk.Action ("copyAction1", global::Mono.Unix.Catalog.GetString ("Copy Row"), null, "gtk-copy");
		this.copyAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Copy");
		w1.Add (this.copyAction1, null);
		this.pasteAction1 = new global::Gtk.Action ("pasteAction1", global::Mono.Unix.Catalog.GetString ("Paste Row"), null, "gtk-paste");
		this.pasteAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Paste");
		w1.Add (this.pasteAction1, null);
		this.noAction = new global::Gtk.Action ("noAction", global::Mono.Unix.Catalog.GetString ("Cut Row"), null, "gtk-no");
		this.noAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cut");
		w1.Add (this.noAction, "<Primary>x");
		this.Action2 = new global::Gtk.Action ("Action2", global::Mono.Unix.Catalog.GetString ("-"), null, null);
		this.Action2.ShortLabel = global::Mono.Unix.Catalog.GetString ("-");
		w1.Add (this.Action2, null);
		this.removeAction = new global::Gtk.Action ("removeAction", global::Mono.Unix.Catalog.GetString ("delete Row"), null, "gtk-remove");
		this.removeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("delete Row");
		w1.Add (this.removeAction, null);
		this.removeAction1 = new global::Gtk.Action ("removeAction1", global::Mono.Unix.Catalog.GetString ("delete selected Column"), null, "gtk-remove");
		this.removeAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("delete selected Column");
		w1.Add (this.removeAction1, null);
		this.deleteAction = new global::Gtk.Action ("deleteAction", global::Mono.Unix.Catalog.GetString ("delete last Column"), null, "gtk-delete");
		this.deleteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("delete last Column");
		w1.Add (this.deleteAction, null);
		this.addAction2 = new global::Gtk.Action ("addAction2", global::Mono.Unix.Catalog.GetString ("add Row"), null, "gtk-add");
		this.addAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("add Row");
		w1.Add (this.addAction2, null);
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("add Column"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("add Column");
		w1.Add (this.newAction, null);
		this.okAction = new global::Gtk.Action ("okAction", global::Mono.Unix.Catalog.GetString ("first Row as Header"), null, "gtk-ok");
		this.okAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("first Row as Header");
		w1.Add (this.okAction, null);
		this.TextsizeAction = new global::Gtk.Action ("TextsizeAction", global::Mono.Unix.Catalog.GetString ("Textsize"), null, null);
		this.TextsizeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Textsize");
		w1.Add (this.TextsizeAction, null);
		this.nine_Action = new global::Gtk.Action ("nine_Action", global::Mono.Unix.Catalog.GetString ("9"), null, null);
		this.nine_Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("9");
		w1.Add (this.nine_Action, null);
		this.ten_Action = new global::Gtk.Action ("ten_Action", global::Mono.Unix.Catalog.GetString ("10"), null, null);
		this.ten_Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("10");
		w1.Add (this.ten_Action, null);
		this.eleven_Action = new global::Gtk.Action ("eleven_Action", global::Mono.Unix.Catalog.GetString ("11"), null, null);
		this.eleven_Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("11");
		w1.Add (this.eleven_Action, null);
		this.twelve_Action = new global::Gtk.Action ("twelve_Action", global::Mono.Unix.Catalog.GetString ("12"), null, null);
		this.twelve_Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("12");
		w1.Add (this.twelve_Action, null);
		this.thirteen_Action = new global::Gtk.Action ("thirteen_Action", global::Mono.Unix.Catalog.GetString ("13"), null, null);
		this.thirteen_Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("13");
		w1.Add (this.thirteen_Action, null);
		this.fourteen_Action = new global::Gtk.Action ("fourteen_Action", global::Mono.Unix.Catalog.GetString ("14"), null, null);
		this.fourteen_Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("14");
		w1.Add (this.fourteen_Action, null);
		this.eighteen_Action = new global::Gtk.Action ("eighteen_Action", global::Mono.Unix.Catalog.GetString ("18"), null, null);
		this.eighteen_Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("18");
		w1.Add (this.eighteen_Action, null);
		this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction, null);
		this.propertiesAction = new global::Gtk.Action ("propertiesAction", global::Mono.Unix.Catalog.GetString ("show / hide Toolbar"), null, "gtk-properties");
		this.propertiesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("show / hide Toolbar");
		w1.Add (this.propertiesAction, null);
		this.dndAction = new global::Gtk.Action ("dndAction", global::Mono.Unix.Catalog.GetString ("New"), null, "gtk-dnd");
		this.dndAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.dndAction, "<Primary>n");
		this.RecentFilesAction = new global::Gtk.Action ("RecentFilesAction", global::Mono.Unix.Catalog.GetString ("Recent Files"), null, null);
		this.RecentFilesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Recent Files");
		w1.Add (this.RecentFilesAction, null);
		this.clearAction = new global::Gtk.Action ("clearAction", global::Mono.Unix.Catalog.GetString ("clear Listbox"), null, "gtk-clear");
		this.clearAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("clear Listbox");
		w1.Add (this.clearAction, null);
		this.dialogInfoAction1 = new global::Gtk.Action ("dialogInfoAction1", global::Mono.Unix.Catalog.GetString ("Info"), null, "gtk-dialog-info");
		this.dialogInfoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Info");
		w1.Add (this.dialogInfoAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='dndAction' action='dndAction'/><menuitem name='openAction' action='openAction'/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction1' action='saveAsAction1'/><separator/><menuitem name='printAction1' action='printAction1'/><separator/><menuitem name='quitAction' action='quitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='copyAction1' action='copyAction1'/><menuitem name='pasteAction1' action='pasteAction1'/><menuitem name='noAction' action='noAction'/><separator/><menuitem name='okAction' action='okAction'/><separator/><menuitem name='addAction2' action='addAction2'/><menuitem name='newAction' action='newAction'/><separator/><menuitem name='removeAction' action='removeAction'/><menuitem name='removeAction1' action='removeAction1'/><menuitem name='deleteAction' action='deleteAction'/><separator/><menuitem name='clearAction' action='clearAction'/></menu><menu name='TextsizeAction' action='TextsizeAction'><menuitem name='nine_Action' action='nine_Action'/><menuitem name='ten_Action' action='ten_Action'/><menuitem name='eleven_Action' action='eleven_Action'/><menuitem name='twelve_Action' action='twelve_Action'/><menuitem name='thirteen_Action' action='thirteen_Action'/><menuitem name='fourteen_Action' action='fourteen_Action'/><menuitem name='eighteen_Action' action='eighteen_Action'/></menu><menu name='ViewAction' action='ViewAction'><menuitem name='propertiesAction' action='propertiesAction'/><menuitem name='dialogInfoAction1' action='dialogInfoAction1'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='dndAction1' action='dndAction1'/><toolitem name='btnOpenFile' action='btnOpenFile'/><toolitem name='btnSaveAction' action='btnSaveAction'/><toolitem name='harddiskAction1' action='harddiskAction1'/><separator/><toolitem name='applyHeader' action='applyHeader'/><separator/><toolitem name='closeAction' action='closeAction'/><toolitem name='addAction1' action='addAction1'/><toolitem name='addAction' action='addAction'/><separator/><toolitem name='copyAction' action='copyAction'/><toolitem name='pasteAction' action='pasteAction'/><toolitem name='cutAction' action='cutAction'/><separator/><toolitem name='justifyLeftAction' action='justifyLeftAction'/><toolitem name='justifyCenterAction' action='justifyCenterAction'/><toolitem name='justifyRightAction' action='justifyRightAction'/><separator/><toolitem name='dialogInfoAction' action='dialogInfoAction'/><separator/><toolitem name='printAction' action='printAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.toolbar1.IconSize = ((global::Gtk.IconSize)(2));
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(2));
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(3));
		this.GtkScrolledWindow.BorderWidth = ((uint)(10));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.lb = new global::Gtk.NodeView ();
		this.lb.CanFocus = true;
		this.lb.Name = "lb";
		this.lb.Reorderable = true;
		this.lb.RulesHint = true;
		this.GtkScrolledWindow.Add (this.lb);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w5.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 770;
		this.DefaultHeight = 381;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.dndAction1.Activated += new global::System.EventHandler (this.NewFile);
		this.btnOpenFile.Activated += new global::System.EventHandler (this.onOpenFile);
		this.btnSaveAction.Activated += new global::System.EventHandler (this.OnSaveFile);
		this.closeAction.Activated += new global::System.EventHandler (this.RemoveSelectedRows);
		this.applyHeader.Activated += new global::System.EventHandler (this.onChangeIcon);
		this.addAction1.Activated += new global::System.EventHandler (this.onAddRow);
		this.copyAction.Activated += new global::System.EventHandler (this.onCopyRow);
		this.pasteAction.Activated += new global::System.EventHandler (this.onPasteRow);
		this.cutAction.Activated += new global::System.EventHandler (this.onCutRow);
		this.addAction.Activated += new global::System.EventHandler (this.onAddColumn);
		this.harddiskAction1.Activated += new global::System.EventHandler (this.onSaveAs);
		this.harddiskAction.Activated += new global::System.EventHandler (this.onTest);
		this.selectFontAction.Activated += new global::System.EventHandler (this.onChangeFont);
		this.justifyCenterAction.Activated += new global::System.EventHandler (this.onCenter);
		this.justifyLeftAction.Activated += new global::System.EventHandler (this.onLeft);
		this.justifyRightAction.Activated += new global::System.EventHandler (this.onRight);
		this.dialogInfoAction.Activated += new global::System.EventHandler (this.onInfo);
		this.preferencesAction.Activated += new global::System.EventHandler (this.onTest);
		this.printAction.Activated += new global::System.EventHandler (this.onPrinting);
		this.openAction.Activated += new global::System.EventHandler (this.onOpenFile);
		this.saveAction.Activated += new global::System.EventHandler (this.OnSaveFile);
		this.saveAsAction1.Activated += new global::System.EventHandler (this.onSaveAs);
		this.printAction1.Activated += new global::System.EventHandler (this.onPrinting);
		this.quitAction.Activated += new global::System.EventHandler (this.onQuit);
		this.copyAction1.Activated += new global::System.EventHandler (this.onCopyRow);
		this.pasteAction1.Activated += new global::System.EventHandler (this.onPasteRow);
		this.noAction.Activated += new global::System.EventHandler (this.onCutRow);
		this.removeAction.Activated += new global::System.EventHandler (this.RemoveSelectedRows);
		this.removeAction1.Activated += new global::System.EventHandler (this.onRemoveSelColumn);
		this.deleteAction.Activated += new global::System.EventHandler (this.onRemoveLastColumn);
		this.addAction2.Activated += new global::System.EventHandler (this.onAddRow);
		this.newAction.Activated += new global::System.EventHandler (this.onAddColumn);
		this.okAction.Activated += new global::System.EventHandler (this.onMakeFirstRowHeader);
		this.nine_Action.Activated += new global::System.EventHandler (this.onSize_nine);
		this.ten_Action.Activated += new global::System.EventHandler (this.onSize_ten);
		this.eleven_Action.Activated += new global::System.EventHandler (this.onSize_eleven);
		this.twelve_Action.Activated += new global::System.EventHandler (this.onSize_twelve);
		this.thirteen_Action.Activated += new global::System.EventHandler (this.onSize_thirteen);
		this.fourteen_Action.Activated += new global::System.EventHandler (this.onSize_fourteen);
		this.eighteen_Action.Activated += new global::System.EventHandler (this.onSize_eighteen);
		this.propertiesAction.Activated += new global::System.EventHandler (this.onHideToolbar);
		this.dndAction.Activated += new global::System.EventHandler (this.NewFile);
		this.clearAction.Activated += new global::System.EventHandler (this.onClearListbox);
		this.dialogInfoAction1.Activated += new global::System.EventHandler (this.onInfo);
	}
}
